### ISSUE TITLE
Sojourn time parametric modelisation

### ISSUE THREAD

**Issue by rtrepos** [poypoyan/edhsmm#16]
Hello poypoyan,
It looks like the sojourn time is modeled as non parametric distribution, will you consider in the future to provide parametric modelisation of the sojourn time such as the Poisson distribution ? (In order to address problems with large sojourn time in hidden states).
Thank you again.
Best
Ronan

**Comment by poypoyan** [comment]
Hello,

Yes, I considered that before (see https://github.com/poypoyan/edhsmm/issues/7). However, I still do not have enough idea on how to implement that :(. I'll take note of this, but this is less priority to me than the censoring testing.

Thanks!
poypoyan

**Comment by poypoyan** [comment]
Hello,

Apologies, but I'll not work on this anymore, because I'll archive this repo, see #20.

Thank you,
poypoyan
