### ISSUE TITLE
Trying to create HSMM with left-to-right assumption

### ISSUE THREAD

**Issue by thanoskont** [poypoyan/edhsmm#18]
So I have been trying to fit a Gaussian HSMM to an observation sequence with monotonic behaviour.
![Figure_1](https://github.com/poypoyan/edhsmm/assets/135984271/2ae98dd1-6e44-4605-ba8e-9113680c5e19)
This observation sequence is created with the sample method from a pre initialized HSMM with parameters:

def init4shortMC(hsmm_class):
    #initial probability
    hsmm_class.pi = np.zeros(5)
    hsmm_class.pi[0]=1

    # durations
    hsmm_class.dur = np.zeros((5,30))
    x = np.linspace(0, 30, 30)
    y = np.zeros_like(x)

    for i in range(len(hsmm_class.dur)):
        for j in range(len(hsmm_class.dur[i])):
            hsmm_class.dur[i, j] = scipy.stats.norm(30, 10).pdf(x[j,])

    for i in range(len(hsmm_class.dur)):
        hsmm_class.dur[i, 14] += 1 - hsmm_class.dur[i].sum()

    #transition matrix
    num_of_states = 5
    hsmm_class.tmat = np.zeros((num_of_states,num_of_states))

    for i in range(len(hsmm_class.tmat)):
        for j in range(len(hsmm_class.tmat[i]) - 1):
            if i == j and j < len(hsmm_class.tmat[i]) - 2:
                hsmm_class.tmat[i, j + 1] = 0.6
                hsmm_class.tmat[i, j + 2] = 0.4
            elif i == j and j == len(hsmm_class.tmat[i]) - 2:
                hsmm_class.tmat[i, j + 1] = 1

    hsmm_class.tmat[-1, -1] = 1

    hsmm_class.mean = np.array([10, 20, 30, 40, 50])   # shape should be (n_states, n_dim)
    hsmm_class.mean = np.reshape(hsmm_class.mean,(-1,1))
    hsmm_class.covmat = np.array([   # shape should be (n_states, n_dim, n_dim) -> array of square matrices
        [[10.]],
        [[10.]],
        [[10.]],
        [[10.]],
        [[10.]],

    ])
```
R1 = GaussianHSMM(n_states=5, n_durations=30, n_iter=100)

init4shortMC(R1)
sample1=R1.sample(100)
```
Then I am trying to fit a newly initialized model to the observation sequence. In order for the model to capture the monotonic sequence, I initialize it with the following start prob and tmat:
```
def init4fit(hsmm_class):
    # initial probability
    hsmm_class.pi = np.zeros(5)
    hsmm_class.pi[0] = 1

    # transition matrix
    num_of_states = 5
    hsmm_class.tmat = np.zeros((num_of_states, num_of_states))

    for i in range(len(hsmm_class.tmat)):
        for j in range(len(hsmm_class.tmat[i]) - 1):
            if i == j and j < len(hsmm_class.tmat[i]) - 2:
                hsmm_class.tmat[i, j + 1] = 0.6
                hsmm_class.tmat[i, j + 2] = 0.4
            elif i == j and j == len(hsmm_class.tmat[i]) - 2:
                hsmm_class.tmat[i, j + 1] = 1

    hsmm_class.tmat[-1, -1] = 1
```

Then I call the .fit method, with the tmat and start prob frozen so that they are not updated during the EM algorithm. However, the model never converges and outputs nan as the mean, durations and covar matrixes. 

Any ideas?

**Comment by poypoyan** [comment]
Hello. Will look into this.

I would say for now that I didn't have the left-to-right assumption in mind when I implemented this, so it is likely that I'll add support to the assumption. But I'll look for a work-around.

Thanks!

**Comment by thanoskont** [comment]
Thank you for your reply!

**Comment by poypoyan** [comment]
Hello.

I cannot get myself to work on this repo anymore 😓. Because of this, I am in the process of archiving this repo. I am sorry that I cannot work on resolving this issue. Thank you for your interest and understanding.

poypoyan
