### ISSUE TITLE
Multi-Dimensional Feature Space

### ISSUE THREAD

**Issue by Hongbo-UOM** [poypoyan/edhsmm#3]
Could you please give a hint, how I can fit model parameters using high dimensional data. For example if I have Data(n*p) n-> number of observation and p -> dimension of observation.

**Comment by poypoyan** [comment]
@zhongbo-THU As of writing this, only one-dimensional data is supported, but I am now working on this. I will create a new branch once I make it work. Thanks!

**Comment by Hongbo-UOM** [comment]
> @zhongbo-THU As of writing this, only one-dimensional data is supported, but I am now working on this. I will create a new branch once I make it work. Thanks!

Thank you very much for your reply and your open source code, very much look forward to your project to support multi-dimensional data operation, which will provide a more perfect reference for developers. I don't know if it's convenient for you to provide a contact or email address, which makes it easier to communicate with each other.

**Comment by poypoyan** [comment]
@zhongbo-THU Check out the [multi-dim branch](https://github.com/poypoyan/edhsmm/tree/multi-dim). The emissions are multivariate normal distribution. For this version:
- The observation must have shape of `(num_of_samples, num_of_dim)`.
- The `<GaussianHSMM object>.mean` must have shape of `(num_of_states, num_of_dim)`.
- The  `<GaussianHSMM object>.covmat` must have shape of `(num_of_states, num_of_dim, num_of_dim)` (in other words, array of covariance matrices).

If there is no manual setting for `mean` and `covmat`, the default `mean` (for now) is just 'zeros' with shape as above (in the future, use K-means), and the default `covmat` is array of identity matrices per state.

The 'tutorial' in this branch is still a test of one-dimensional data. Actual testing of multi-dimensional data is appreciated.

You can contact me at `srazin123@gmail.com`. Thanks!

**Comment by poypoyan** [comment]
**Update:** multi-dim branch is now merged to master, because I already did a preliminary "test" for 2-dimensional observations (see [Notebooks](https://github.com/poypoyan/edhsmm/tree/master/notebooks)).

I will now close this issue, but comments are, of course, still welcome. Thanks! 😄

**Comment by Hongbo-UOM** [comment]
very thanks～
